name: $(Major).$(Minor).$(rev:r)  # build numbering format

trigger: none

resources:
  repositories: # the test data
    - repository: VSTSBuildTaskValidation
      type: git
      name: VSTSBuildTaskValidation
      branch: master

variables:
  # declared in the pipeline UI
  #  major
  #  minor
  - group:  'WIKIPDFExport Extension'
    # this group includes the following variables
    #  ExtensionRoot - working folder
    #  PublisherID  - Marketplace publisher
    #  ExtensionID - Marketplace extension id
    #  vmImage - name of Azure DevOps pool to use
    #  artifactLocationName -  folder the artifact to push is stored in
    #  privateExtentionsTag - tag to show if private (else blank)
    #  taskID - Marketplace ID of task
    #  wikiFilename - name of generated docs files
    #  githubPAT - for testing
    #  AzureDevOpsPAT - for testing
stages:

  - stage: Test
    jobs:
    - deployment: Private_Tests_Mac
      timeoutInMinutes: 0
      environment: 'Azure DevOps Marketplace (WIKIPDFExport)'
      pool:
        vmImage: 'macOS-latest'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: test-stage.yml
